name: Release

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: 'true'

      - name: Prepare dependencies (Xcode)
        run: |
          sudo xcode-select -s /Applications/Xcode_26.3.0.app

      - name: Build
        run: | 
          agvtool new-version -all $(git rev-parse HEAD)
          make

      - name: Get Version
        id: get_version
        run: |
          unzip -p upload/Feather.ipa Payload/Feather.app/Info.plist > /tmp/Feather-Info.plist
          VERSION=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" /tmp/Feather-Info.plist)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Create Release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v3.0.2
        with:
          name: Feather v${{ env.VERSION }}
          tag_name: v${{ env.VERSION }}
          files: |
            packages/*
          generate_release_notes: true
          fail_on_unmatched_files: true
          draft: true
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
